name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:

      # Workaround for https://github.com/googleapis/release-please-action/issues/1074
      - name: Add labels to the repository if not present
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh label create "autorelease: pending" || true
          gh label create "autorelease: tagged" || true
          gh label create "autorelease: snapshot" || true
          gh label create "autorelease: published" || true
              
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: node
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: ${{ needs.version.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
